version: "3"
services:
    app:
        image: maxbnet/perseverance
        container_name: perseverance
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Develop
            - ASPNETCORE_URLS=http://0.0.0.0:5000
            - USE_AZURE_SIGNALR=false
        ports:
            - "5000:5000"    